// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cities.sql

package db

import (
	"context"
)

const getCityByID = `-- name: GetCityByID :one
SELECT id, name, created_at, updated_at FROM cities 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCityByID(ctx context.Context, id int32) (City, error) {
	row := q.db.QueryRow(ctx, getCityByID, id)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCityByName = `-- name: GetCityByName :one
SELECT id, name, created_at, updated_at FROM cities 
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetCityByName(ctx context.Context, name string) (City, error) {
	row := q.db.QueryRow(ctx, getCityByName, name)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCities = `-- name: ListCities :many
SELECT id, name, created_at, updated_at FROM cities 
ORDER BY name ASC
`

func (q *Queries) ListCities(ctx context.Context) ([]City, error) {
	rows, err := q.db.Query(ctx, listCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []City
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
